using RicOneApi.Common.Objects;
using RicOneApi.Models.XPress;

namespace RicOneApi.Interfaces
{
    public interface IXPress
    {
        void CreateXStaffUsers(string refId);
        void CreateXStudentUsers(string refId);
        void DeleteXStaffUsernamesPasswords(string refId);
        void DeleteXStaffUsers(string refId);
        void DeleteXStudentUsernamesPasswords(string refId);
        void DeleteXStudentUsers(string refId);
        int GetLastPage(ServicePath servicePath, int? navigationPageSize);
        int GetLastPage(ServicePath servicePath, int? navigationPageSize, int? schoolYear);
        int GetLastPage(ServicePath servicePath, int? navigationPageSize, string opaqueMarker);
        int GetLastPage(ServicePath servicePath, string refId, int? navigationPageSize);
        int GetLastPage(ServicePath servicePath, string refId, int? navigationPageSize, int? schoolYear);
        ResponseSingle<XCalendarType> GetXCalendar(string refId);
        ResponseSingle<XCalendarType> GetXCalendar(string refId, int? schoolYear);
        ResponseMulti<XCalendarType> GetXCalendars();
        ResponseMulti<XCalendarType> GetXCalendars(int? schoolYear);
        ResponseMulti<XCalendarType> GetXCalendars(int? navigationPage, int? navigationPageSize);
        ResponseMulti<XCalendarType> GetXCalendars(int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XCalendarType> GetXCalendars(int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XCalendarType> GetXCalendars(string opaqueMarker);
        ResponseMulti<XCalendarType> GetXCalendarsByXLea(string refId);
        ResponseMulti<XCalendarType> GetXCalendarsByXLea(string refId, int? schoolYear);
        ResponseMulti<XCalendarType> GetXCalendarsByXLea(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XCalendarType> GetXCalendarsByXLea(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XCalendarType> GetXCalendarsByXLea(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XCalendarType> GetXCalendarsByXLea(string refId, string opaqueMarker);
        ResponseMulti<XCalendarType> GetXCalendarsByXSchool(string refId);
        ResponseMulti<XCalendarType> GetXCalendarsByXSchool(string refId, int? schoolYear);
        ResponseMulti<XCalendarType> GetXCalendarsByXSchool(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XCalendarType> GetXCalendarsByXSchool(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XCalendarType> GetXCalendarsByXSchool(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XCalendarType> GetXCalendarsByXSchool(string refId, string opaqueMarker);
        ResponseSingle<XContactType> GetXContact(string refId);
        ResponseSingle<XContactType> GetXContact(string refId, int? schoolYear);
        ResponseMulti<XContactType> GetXContacts();
        ResponseMulti<XContactType> GetXContacts(int? schoolYear);
        ResponseMulti<XContactType> GetXContacts(int? navigationPage, int? navigationPageSize);
        ResponseMulti<XContactType> GetXContacts(int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XContactType> GetXContacts(int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XContactType> GetXContacts(string opaqueMarker);
        ResponseMulti<XContactType> GetXContactsByXLea(string refId);
        ResponseMulti<XContactType> GetXContactsByXLea(string refId, int? schoolYear);
        ResponseMulti<XContactType> GetXContactsByXLea(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XContactType> GetXContactsByXLea(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XContactType> GetXContactsByXLea(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XContactType> GetXContactsByXLea(string refId, string opaqueMarker);
        ResponseMulti<XContactType> GetXContactsByXSchool(string refId);
        ResponseMulti<XContactType> GetXContactsByXSchool(string refId, int? schoolYear);
        ResponseMulti<XContactType> GetXContactsByXSchool(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XContactType> GetXContactsByXSchool(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XContactType> GetXContactsByXSchool(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XContactType> GetXContactsByXSchool(string refId, string opaqueMarker);
        ResponseMulti<XContactType> GetXContactsByXStudent(string refId);
        ResponseMulti<XContactType> GetXContactsByXStudent(string refId, int? schoolYear);
        ResponseMulti<XContactType> GetXContactsByXStudent(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XContactType> GetXContactsByXStudent(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XContactType> GetXContactsByXStudent(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XContactType> GetXContactsByXStudent(string refId, string opaqueMarker);
        ResponseSingle<XCourseType> GetXCourse(string refId);
        ResponseSingle<XCourseType> GetXCourse(string refId, int? schoolYear);
        ResponseMulti<XCourseType> GetXCourses();
        ResponseMulti<XCourseType> GetXCourses(int? shcoolYear);
        ResponseMulti<XCourseType> GetXCourses(int? navigationPage, int? navigationPageSize);
        ResponseMulti<XCourseType> GetXCourses(int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XCourseType> GetXCourses(int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XCourseType> GetXCourses(string opaqueMarker);
        ResponseMulti<XCourseType> GetXCoursesByXLea(string refId);
        ResponseMulti<XCourseType> GetXCoursesByXLea(string refId, int? schoolYear);
        ResponseMulti<XCourseType> GetXCoursesByXLea(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XCourseType> GetXCoursesByXLea(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XCourseType> GetXCoursesByXLea(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XCourseType> GetXCoursesByXLea(string refId, string opaqueMarker);
        ResponseMulti<XCourseType> GetXCoursesByXRoster(string refId);
        ResponseMulti<XCourseType> GetXCoursesByXRoster(string refId, int? schoolYear);
        ResponseMulti<XCourseType> GetXCoursesByXRoster(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XCourseType> GetXCoursesByXRoster(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XCourseType> GetXCoursesByXRoster(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XCourseType> GetXCoursesByXRoster(string refId, string opaqueMarker);
        ResponseMulti<XCourseType> GetXCoursesByXSchool(string refId);
        ResponseMulti<XCourseType> GetXCoursesByXSchool(string refId, int? schoolYear);
        ResponseMulti<XCourseType> GetXCoursesByXSchool(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XCourseType> GetXCoursesByXSchool(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XCourseType> GetXCoursesByXSchool(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XCourseType> GetXCoursesByXSchool(string refId, string opaqueMarker);
        ResponseSingle<XLeaType> GetXLea(string refId);
        ResponseSingle<XLeaType> GetXLea(string refId, int? schoolYear);
        ResponseSingle<XLeaType> GetXLea(string idType, string id);
        ResponseSingle<XLeaType> GetXLea(string idType, string id, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeas();
        ResponseMulti<XLeaType> GetXLeas(int? schoolYear);
        ResponseMulti<XLeaType> GetXLeas(int? navigationPage, int? navigationPageSize);
        ResponseMulti<XLeaType> GetXLeas(int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeas(int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeas(string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeasByXContact(string refId);
        ResponseMulti<XLeaType> GetXLeasByXContact(string refId, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeasByXContact(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XLeaType> GetXLeasByXContact(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeasByXContact(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeasByXContact(string refId, string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeasByXRoster(string refId);
        ResponseMulti<XLeaType> GetXLeasByXRoster(string refId, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeasByXRoster(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XLeaType> GetXLeasByXRoster(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeasByXRoster(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeasByXRoster(string refId, string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeasByXSchool(string refId);
        ResponseMulti<XLeaType> GetXLeasByXSchool(string refId, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeasByXSchool(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XLeaType> GetXLeasByXSchool(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeasByXSchool(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeasByXSchool(string refId, string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeasByXStaff(string refId);
        ResponseMulti<XLeaType> GetXLeasByXStaff(string refId, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeasByXStaff(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XLeaType> GetXLeasByXStaff(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeasByXStaff(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeasByXStaff(string refId, string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeasByXStudent(string refId);
        ResponseMulti<XLeaType> GetXLeasByXStudent(string refId, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeasByXStudent(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XLeaType> GetXLeasByXStudent(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XLeaType> GetXLeasByXStudent(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XLeaType> GetXLeasByXStudent(string refId, string opaqueMarker);
        ResponseSingle<XRosterType> GetXRoster(string refId);
        ResponseSingle<XRosterType> GetXRoster(string refId, int? schoolYear);
        ResponseMulti<XRosterType> GetXRosters();
        ResponseMulti<XRosterType> GetXRosters(int? schoolYear);
        ResponseMulti<XRosterType> GetXRosters(int? navigationPage, int? navigationPageSize);
        ResponseMulti<XRosterType> GetXRosters(int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XRosterType> GetXRosters(int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XRosterType> GetXRosters(string opaqueMarker);
        ResponseMulti<XRosterType> GetXRostersByXCourse(string refId);
        ResponseMulti<XRosterType> GetXRostersByXCourse(string refId, int? schoolYear);
        ResponseMulti<XRosterType> GetXRostersByXCourse(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XRosterType> GetXRostersByXCourse(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XRosterType> GetXRostersByXCourse(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XRosterType> GetXRostersByXCourse(string refId, string opaqueMarker);
        ResponseMulti<XRosterType> GetXRostersByXLea(string refId);
        ResponseMulti<XRosterType> GetXRostersByXLea(string refId, int? schoolYear);
        ResponseMulti<XRosterType> GetXRostersByXLea(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XRosterType> GetXRostersByXLea(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XRosterType> GetXRostersByXLea(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XRosterType> GetXRostersByXLea(string refId, string opaqueMarker);
        ResponseMulti<XRosterType> GetXRostersByXSchool(string refId);
        ResponseMulti<XRosterType> GetXRostersByXSchool(string refId, int? schoolYear);
        ResponseMulti<XRosterType> GetXRostersByXSchool(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XRosterType> GetXRostersByXSchool(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XRosterType> GetXRostersByXSchool(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XRosterType> GetXRostersByXSchool(string refId, string opaqueMarker);
        ResponseMulti<XRosterType> GetXRostersByXStaff(string refId);
        ResponseMulti<XRosterType> GetXRostersByXStaff(string refId, int? schoolYear);
        ResponseMulti<XRosterType> GetXRostersByXStaff(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XRosterType> GetXRostersByXStaff(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XRosterType> GetXRostersByXStaff(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XRosterType> GetXRostersByXStaff(string refId, string opaqueMarker);
        ResponseMulti<XRosterType> GetXRostersByXStudent(string refId);
        ResponseMulti<XRosterType> GetXRostersByXStudent(string refId, int? schoolYear);
        ResponseMulti<XRosterType> GetXRostersByXStudent(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XRosterType> GetXRostersByXStudent(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XRosterType> GetXRostersByXStudent(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XRosterType> GetXRostersByXStudent(string refId, string opaqueMarker);
        ResponseSingle<XSchoolType> GetXSchool(string refId);
        ResponseSingle<XSchoolType> GetXSchool(string refId, int? schoolYear);
        ResponseSingle<XSchoolType> GetXSchool(string idType, string id);
        ResponseSingle<XSchoolType> GetXSchool(string idType, string id, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchools();
        ResponseMulti<XSchoolType> GetXSchools(int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchools(int? navigationPage, int? navigationPageSize);
        ResponseMulti<XSchoolType> GetXSchools(int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchools(int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchools(string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXCalendar(string refId);
        ResponseMulti<XSchoolType> GetXSchoolsByXCalendar(string refId, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXCalendar(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XSchoolType> GetXSchoolsByXCalendar(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXCalendar(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXCalendar(string refId, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXContact(string refId);
        ResponseMulti<XSchoolType> GetXSchoolsByXContact(string refId, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXContact(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XSchoolType> GetXSchoolsByXContact(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXContact(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXContact(string refId, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXCourse(string refId);
        ResponseMulti<XSchoolType> GetXSchoolsByXCourse(string refId, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXCourse(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XSchoolType> GetXSchoolsByXCourse(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXCourse(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXCourse(string refId, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXLea(string refId);
        ResponseMulti<XSchoolType> GetXSchoolsByXLea(string refId, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXLea(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XSchoolType> GetXSchoolsByXLea(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXLea(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXLea(string refId, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXRoster(string refId);
        ResponseMulti<XSchoolType> GetXSchoolsByXRoster(string refId, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXRoster(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XSchoolType> GetXSchoolsByXRoster(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXRoster(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXRoster(string refId, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXStaff(string refId);
        ResponseMulti<XSchoolType> GetXSchoolsByXStaff(string refId, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXStaff(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XSchoolType> GetXSchoolsByXStaff(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXStaff(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXStaff(string refId, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXStudent(string refId);
        ResponseMulti<XSchoolType> GetXSchoolsByXStudent(string refId, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXStudent(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XSchoolType> GetXSchoolsByXStudent(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XSchoolType> GetXSchoolsByXStudent(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XSchoolType> GetXSchoolsByXStudent(string refId, string opaqueMarker);
        ResponseSingle<XStaffType> GetXStaff(string refId);
        ResponseSingle<XStaffType> GetXStaff(string refId, int? schoolYear);
        ResponseSingle<XStaffType> GetXStaff(string idType, string id);
        ResponseSingle<XStaffType> GetXStaff(string idType, string id, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffs();
        ResponseMulti<XStaffType> GetXStaffs(int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffs(int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStaffType> GetXStaffs(int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffs(int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffs(string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffsByXCourse(string refId);
        ResponseMulti<XStaffType> GetXStaffsByXCourse(string refId, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffsByXCourse(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStaffType> GetXStaffsByXCourse(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffsByXCourse(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffsByXCourse(string refId, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffsByXLea(string refId);
        ResponseMulti<XStaffType> GetXStaffsByXLea(string refId, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffsByXLea(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStaffType> GetXStaffsByXLea(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffsByXLea(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffsByXLea(string refId, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffsByXRoster(string refId);
        ResponseMulti<XStaffType> GetXStaffsByXRoster(string refId, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffsByXRoster(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStaffType> GetXStaffsByXRoster(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffsByXRoster(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffsByXRoster(string refId, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffsByXSchool(string refId);
        ResponseMulti<XStaffType> GetXStaffsByXSchool(string refId, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffsByXSchool(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStaffType> GetXStaffsByXSchool(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffsByXSchool(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffsByXSchool(string refId, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffsByXStudent(string refId);
        ResponseMulti<XStaffType> GetXStaffsByXStudent(string refId, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffsByXStudent(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStaffType> GetXStaffsByXStudent(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStaffType> GetXStaffsByXStudent(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffsByXStudent(string refId, string opaqueMarker);
        ResponseMulti<XStaffType> GetXStaffUsers(string refId);
        ResponseMulti<XStaffType> GetXStaffUsers(string refId, int? navigationPage, int? navigationPageSize);
        ResponseSingle<XStudentType> GetXStudent(string refId);
        ResponseSingle<XStudentType> GetXStudent(string refId, int? schoolYear);
        ResponseSingle<XStudentType> GetXStudent(string idType, string id);
        ResponseSingle<XStudentType> GetXStudent(string idType, string id, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudents();
        ResponseMulti<XStudentType> GetXStudents(int? schoolYear);
        ResponseMulti<XStudentType> GetXStudents(int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStudentType> GetXStudents(int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudents(int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudents(string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentsByXContact(string refId);
        ResponseMulti<XStudentType> GetXStudentsByXContact(string refId, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudentsByXContact(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStudentType> GetXStudentsByXContact(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudentsByXContact(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentsByXContact(string refId, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentsByXLea(string refId);
        ResponseMulti<XStudentType> GetXStudentsByXLea(string refId, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudentsByXLea(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStudentType> GetXStudentsByXLea(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudentsByXLea(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentsByXLea(string refId, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentsByXRoster(string refId);
        ResponseMulti<XStudentType> GetXStudentsByXRoster(string refId, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudentsByXRoster(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStudentType> GetXStudentsByXRoster(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudentsByXRoster(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentsByXRoster(string refId, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentsByXSchool(string refId);
        ResponseMulti<XStudentType> GetXStudentsByXSchool(string refId, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudentsByXSchool(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStudentType> GetXStudentsByXSchool(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudentsByXSchool(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentsByXSchool(string refId, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentsByXStaff(string refId);
        ResponseMulti<XStudentType> GetXStudentsByXStaff(string refId, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudentsByXStaff(string refId, int? navigationPage, int? navigationPageSize);
        ResponseMulti<XStudentType> GetXStudentsByXStaff(string refId, int? navigationPage, int? navigationPageSize, int? schoolYear);
        ResponseMulti<XStudentType> GetXStudentsByXStaff(string refId, int? navigationPage, int? navigationPageSize, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentsByXStaff(string refId, string opaqueMarker);
        ResponseMulti<XStudentType> GetXStudentUsers(string refId);
        ResponseMulti<XStudentType> GetXStudentUsers(string refId, int? navigationPage, int? navigationPageSize);
    }
}